######################################################################
# Automatically generated by qmake (3.1) Fri Jan 13 17:33:49 2017
######################################################################

TEMPLATE = app
TARGET = cpuburn
INCLUDEPATH += .

# Input
SOURCES += main.cpp impl.cpp

CONFIG += force_debug_info console
